name: master

on:
   push:
      paths-ignore:
         - 'doc/**'
         - 'documentation/**'
         - '*.md'
         - '*.yml'
         - '.github/workflows/**'
         - '.github/actions/**'
      branches:
         - master

permissions:
   contents: read

env:
   RELEASE_VERSION: ${{ github.event.inputs.version }}
   OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
   OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
   ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
   ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
   ORG_GRADLE_PROJECT_Kotest_GradleBuildCache_user: ${{ secrets.GRADLE_BUILD_CACHE_USER }}
   ORG_GRADLE_PROJECT_Kotest_GradleBuildCache_pass: ${{ secrets.GRADLE_BUILD_CACHE_PASS }}

jobs:
   validate-primary:
      runs-on: ubuntu-latest
      steps:
         -  name: Setup build
            uses: ./.github/actions/setup-build
            with:
               cc-encryption-key: ${{ secrets.GRADLE_CONFIGURATION_CACHE_ENCRYPTION_KEY }}

         -  name: Validate API & tests
            run: ./gradlew apiCheck check --scan --stacktrace

         -  name: Post build
            uses: ./.github/actions/post-build

   validate-secondary:
      name: Validate on secondary runners

      needs: [ validate-primary ]
      strategy:
         matrix:
            include:
               -  os: macos-latest
               -  os: windows-latest
         fail-fast: false
      runs-on: ${{ matrix.os }}
      steps:
          -  name: Setup build
             uses: ./.github/actions/setup-build
             with:
              cc-encryption-key: ${{ secrets.GRADLE_CONFIGURATION_CACHE_ENCRYPTION_KEY }}

          -  name: Validate tests
             run: ./gradlew check --scan --stacktrace

          -  name: Post build
             uses: ./.github/actions/post-build

   publish-sonatype:
      name: Publish all artifacts to Sonatype (Maven Central)
      runs-on: macos-latest
      needs: [ validate-primary, validate-secondary ]
      steps:
         -  name: Setup build
            uses: ./.github/actions/setup-build
            with:
               cc-encryption-key: ${{ secrets.GRADLE_CONFIGURATION_CACHE_ENCRYPTION_KEY }}

         # TODO remove `--continue` when Kotest Gradle Plugin publishing works
         #      https://github.com/kotest/kotest/issues/4012#issuecomment-2241294938
         -  name: Validate tests
            run: ./gradlew publishAllPublicationsToDeployRepository --scan --stacktrace --continue

         -  name: Post build
            uses: ./.github/actions/post-build

